### PR TITLE
fix initial height 0

### LINKED ISSUE #12: Initial height set to 0
When running the example in Chrome, the inner iframe height was set to 0, making the output invisible.
It became visible when I opened the devtools (on resize).
[This commit from a fork](https://github.com/quartzmo/stuff.js/commit/703d8081f84ceec2c12d8cee493d80b2c6ee4f27) solves that problem for me.
Could this be fixed here too? (I can make a pull request with the same fix if you want.)

### PR DESCRIPTION
**Pull request by hermansje**
fixes #12

### CODE REVIEW

**Comment by hermansje** [comment]
I tested this (on Windows) in Chrome, Firefox, IE and Edge.

**Comment by amasad** [comment]
Hey sorry for the late reply. I think you're right. But it can be solved just in css with something like:

```css
html, body, iframe {
  height: 100%;
  width: 100%;
}
```

Also, I'm not sure why `position` needs to be absolute?

**Comment by amasad** [comment]
fixed via 91e5bc4b98b47ebc6227b380d4c0f9c8074246e7

**Comment by hermansje** [comment]
I started from code of a fork, but this css-solution is cleaner of course. Thank you for fixing it!

**Pull request closed without merging**
